""""Link_photo_to_photographer_remove_from_event"

Revision ID: 00c331d49b40
Revises: 4496b059854c
Create Date: 2025-05-05 19:11:32.262094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c331d49b40'
down_revision = '4496b059854c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        # Provide a name for the constraint to be dropped
        # Replace 'fk_events_photographer_id_users' if your actual constraint name is different
        # batch_op.drop_constraint('fk_events_photographer_id_users', type_='foreignkey') # Commented out: drop_column handles this in batch
        batch_op.drop_column('photographer_id')

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photographer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_photos_photographer_id_users', 'users', ['photographer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_photos_photographer_id_users', type_='foreignkey')
        batch_op.drop_column('photographer_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photographer_id', sa.INTEGER(), nullable=True))
        # Use the same name when recreating the constraint in downgrade
        # batch_op.create_foreign_key('fk_events_photographer_id_users', 'users', ['photographer_id'], ['id']) # Commented out corresponding line

    # ### end Alembic commands ###
