"""add clerk_id to users table

Revision ID: 698f3c8ebba2
Revises: e07330591f44
Create Date: 2025-05-05 22:01:46.692595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698f3c8ebba2'
down_revision = 'e07330591f44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clerk_id', sa.String(), nullable=True))
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_clerk_id'), ['clerk_id'], unique=True)
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_clerk_id'))
        batch_op.create_index('ix_users_username', ['username'], unique=1)
        batch_op.drop_column('clerk_id')

    # ### end Alembic commands ###
