""""Add_EventPhotographerPrice_table_remove_price_from_Event"

Revision ID: e07330591f44
Revises: 00c331d49b40
Create Date: 2025-05-05 19:15:43.664029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07330591f44'
down_revision = '00c331d49b40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_photographer_prices',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('photographer_id', sa.Integer(), nullable=False),
    sa.Column('price_per_photo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['photographer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'photographer_id'),
    sa.UniqueConstraint('event_id', 'photographer_id', name='uq_event_photographer_price')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('price_per_photo')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_photo', sa.INTEGER(), nullable=True))

    op.drop_table('event_photographer_prices')
    # ### end Alembic commands ###
